# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import multi_service_pb2 as multi__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in multi_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPersonById = channel.unary_unary(
                '/PersonService/GetPersonById',
                request_serializer=multi__service__pb2.PersonIdRequest.SerializeToString,
                response_deserializer=multi__service__pb2.PersonResponse.FromString,
                _registered_method=True)
        self.CreatePerson = channel.unary_unary(
                '/PersonService/CreatePerson',
                request_serializer=multi__service__pb2.CreatePersonRequest.SerializeToString,
                response_deserializer=multi__service__pb2.CreatePersonResponse.FromString,
                _registered_method=True)
        self.ListPersons = channel.unary_stream(
                '/PersonService/ListPersons',
                request_serializer=multi__service__pb2.Empty.SerializeToString,
                response_deserializer=multi__service__pb2.PersonResponse.FromString,
                _registered_method=True)
        self.DeletePersonById = channel.unary_unary(
                '/PersonService/DeletePersonById',
                request_serializer=multi__service__pb2.PersonIdRequest.SerializeToString,
                response_deserializer=multi__service__pb2.DeletePersonResponse.FromString,
                _registered_method=True)


class PersonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPersonById(self, request, context):
        """Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePerson(self, request, context):
        """Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPersons(self, request, context):
        """Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePersonById(self, request, context):
        """Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPersonById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonById,
                    request_deserializer=multi__service__pb2.PersonIdRequest.FromString,
                    response_serializer=multi__service__pb2.PersonResponse.SerializeToString,
            ),
            'CreatePerson': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePerson,
                    request_deserializer=multi__service__pb2.CreatePersonRequest.FromString,
                    response_serializer=multi__service__pb2.CreatePersonResponse.SerializeToString,
            ),
            'ListPersons': grpc.unary_stream_rpc_method_handler(
                    servicer.ListPersons,
                    request_deserializer=multi__service__pb2.Empty.FromString,
                    response_serializer=multi__service__pb2.PersonResponse.SerializeToString,
            ),
            'DeletePersonById': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePersonById,
                    request_deserializer=multi__service__pb2.PersonIdRequest.FromString,
                    response_serializer=multi__service__pb2.DeletePersonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PersonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PersonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPersonById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PersonService/GetPersonById',
            multi__service__pb2.PersonIdRequest.SerializeToString,
            multi__service__pb2.PersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PersonService/CreatePerson',
            multi__service__pb2.CreatePersonRequest.SerializeToString,
            multi__service__pb2.CreatePersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPersons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PersonService/ListPersons',
            multi__service__pb2.Empty.SerializeToString,
            multi__service__pb2.PersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePersonById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PersonService/DeletePersonById',
            multi__service__pb2.PersonIdRequest.SerializeToString,
            multi__service__pb2.DeletePersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
