# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: add_grpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'add_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x64\x64_grpc.proto\x12\x08\x61\x64\x64_grpc\"(\n\nAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1c\n\x0b\x41\x64\x64Response\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x05\x32J\n\tAddNumber\x12=\n\x0c\x41\x64\x64TwoNumber\x12\x14.add_grpc.AddRequest\x1a\x15.add_grpc.AddResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'add_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=28
  _globals['_ADDREQUEST']._serialized_end=68
  _globals['_ADDRESPONSE']._serialized_start=70
  _globals['_ADDRESPONSE']._serialized_end=98
  _globals['_ADDNUMBER']._serialized_start=100
  _globals['_ADDNUMBER']._serialized_end=174
# @@protoc_insertion_point(module_scope)
